version: "3.8"

services:
  nginx:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./public:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:8.0.0alpha1-fpm
    volumes:
    - ./public:/var/www/html
